REM @echo off
call SETENV.bat
title %0

REM TODO make these work:
set CMAKE_SOURCEDIR=%ROOTDIR%
set CMAKE_BUILDIR=%BUILDDIR%

%CMAKE% -i -DCMAKE_INSTALL_PREFIX=%INSTALLDIR% -DBUILD_OSG_EXAMPLES=ON -DBUILD_OSG_WRAPPERS=ON %BUILDDIR%
